-- AlterTable
ALTER TABLE `system_settings` MODIFY `category` ENUM('SYSTEM', 'SECURITY', 'NOTIFICATION', 'WEDDING', 'VENUE', 'GUEST', 'SCHEDULE', 'MAP', 'ATTRACTIONS', 'CHAT', 'ANALYTICS', 'UI_UX') NOT NULL;
